<?xml version="1.0" ?>

<!DOCTYPE DOCUMENT[
<!ELEMENT DOCUMENT (CUSTOMER)*>

<!ELEMENT CUSTOMER (NAME, DATE, ORDERS)>

<!ELEMENT NAME (LAST_NAME, FIRST_NAME)>

<!ELEMENT LAST_NAME (#PCDATA)>
<!ELEMENT FIRST_NAME (#PCDATA)>

<!ELEMENT DATE (#PCDATA)>

<!ELEMENT ORDERS (ITEM)*>

<!ELEMENT ITEM (PRODUCT, NUMBER, PRICE)>

<!ELEMENT PRODUCT (#PCDATA)>
<!ELEMENT NUMBER (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>

<!ENTITY TODAY "APRIL 15 2009">
]>
<DOCUMENT>
<CUSTOMER>
<NAME>
	<LAST_NAME> TRIVEDI</LAST_NAME>
	<FIRST_NAME>KAVITA</FIRST_NAME>
</NAME>

<DATE> &TODAY;</DATE>
<ORDERS>
<ITEM>
<PRODUCT>C_PROG</PRODUCT>
<NUMBER>001</NUMBER>
<PRICE> $250</PRICE>
</ITEM>
</ORDERS>
</CUSTOMER>

<CUSTOMER>
<NAME>
	<LAST_NAME> sHARMA</LAST_NAME>
<FIRST_NAME>BHAVESH</FIRST_NAME>
</NAME>
<DATE>&TODAY;</DATE>
<ITEM>
<PRODUCT>JAVA_PROG</PRODUCT>
<NUMBER>002</NUMBER>
<PRICE> $750</PRICE>
</ITEM>
</CUSTOMER>


</DOCUMENT>


